import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "./components/ui/tooltip";
import { AppLayout } from "./components/appLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JM Next.js Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add the Chatbot configuration script */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.chtlConfig = { chatbotId: "5484164381" };
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider delayDuration={0}>
          <AppLayout>{children}</AppLayout>
        </TooltipProvider>

        {/* Add the Chatbot embed script */}
        <script
          async
          data-id="5484164381"
          id="chtl-script"
          type="text/javascript"
          src="https://chatling.ai/js/embed.js"
        ></script>
      </body>
    </html>
  );
}